language: node_js
node_js:
  - "4"
  - "5"
branches:
  only:
    - master
sudo: false
script: "npm run test:cov"

addons:
  code_climate:
    repo_token: $CODE_CLIMATE
after_success:
  - npm install -g codeclimate-test-reporter
  - codeclimate-test-reporter < coverage/lcov.info


